/*
 * VRM API
 *
 * ## Introduction This document provides a brief overview of some of the available endpoints and their parameters. The API is a REST API, accepting JSON as request body. You can use the try-it tool to play around with it, or use software like Postman.  ## Authentication Most endpoints require authentication, using a JWT token. This token should be placed in the `x-authorization` field in the HTTP header. There are two types of tokens. - Bearer token. Uses the `Bearer <token_value>` format. This is used when logging in to VRM, for example. Can be retrieved from [/auth/login](/operations/auth/login) or [/auth/loginAsDemo](/operations/auth/loginAsDemo). - Access token. Uses the `Token <token_value>` format. This is commonly used for third party applications using the VRM API. Can be created using [/users/{idUser}/accesstokens/create](/operations/users/idUser/accesstokens/create).  ## Rate limiting Most endpoints are by default rate limited with a rolling window of max 200 requests, where every 0.33 seconds a request gets removed from the rolling window. (so on average maximum of 3 requests per second won't get rate limited). There are different types of ratelimiting in VRM. If you receive a 429 with a JSON response, you can check the Retry-After response header to check the amount of seconds you have to wait until retrying.  ## WARNING & DISCLAIMER Whilst publicly available, Victron Energy does not offer support to professional customers or end-users that implement features using the here documented functionality, except in really specific situations (i.e such as a special arrangement with a large OEM customer).  The recommended method for support on the VRM API is to use the Modifications section on Victron Community. This space is frequently visited by many people using the API, and other methods of integrating with Victron products. Direct company support is only offered on a limited basis via your Victron representative.
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Xunit;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInner
        //private InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInner instance;

        public InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInnerTests()
        {
            // TODO uncomment below to create an instance of InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInner
            //instance = new InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInner
        /// </summary>
        [Fact]
        public void InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInner
            //Assert.IsType<InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInner>(instance);
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'EnumData'
        /// </summary>
        [Fact]
        public void EnumDataTest()
        {
            // TODO unit test for the property 'EnumData'
        }

        /// <summary>
        /// Test the property 'IdDataAttribute'
        /// </summary>
        [Fact]
        public void IdDataAttributeTest()
        {
            // TODO unit test for the property 'IdDataAttribute'
        }

        /// <summary>
        /// Test the property 'IdDeviceType'
        /// </summary>
        [Fact]
        public void IdDeviceTypeTest()
        {
            // TODO unit test for the property 'IdDeviceType'
        }

        /// <summary>
        /// Test the property 'IdSite'
        /// </summary>
        [Fact]
        public void IdSiteTest()
        {
            // TODO unit test for the property 'IdSite'
        }

        /// <summary>
        /// Test the property 'LoggedTimestamp'
        /// </summary>
        [Fact]
        public void LoggedTimestampTest()
        {
            // TODO unit test for the property 'LoggedTimestamp'
        }

        /// <summary>
        /// Test the property 'LoggedValue'
        /// </summary>
        [Fact]
        public void LoggedValueTest()
        {
            // TODO unit test for the property 'LoggedValue'
        }

        /// <summary>
        /// Test the property 'IdUser'
        /// </summary>
        [Fact]
        public void IdUserTest()
        {
            // TODO unit test for the property 'IdUser'
        }

        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Fact]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }

        /// <summary>
        /// Test the property 'UserName'
        /// </summary>
        [Fact]
        public void UserNameTest()
        {
            // TODO unit test for the property 'UserName'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Fact]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }

        /// <summary>
        /// Test the property 'Values'
        /// </summary>
        [Fact]
        public void ValuesTest()
        {
            // TODO unit test for the property 'Values'
        }
    }
}
