/*
 * VRM API
 *
 * ## Introduction This document provides a brief overview of some of the available endpoints and their parameters. The API is a REST API, accepting JSON as request body. You can use the try-it tool to play around with it, or use software like Postman.  ## Authentication Most endpoints require authentication, using a JWT token. This token should be placed in the `x-authorization` field in the HTTP header. There are two types of tokens. - Bearer token. Uses the `Bearer <token_value>` format. This is used when logging in to VRM, for example. Can be retrieved from [/auth/login](/operations/auth/login) or [/auth/loginAsDemo](/operations/auth/loginAsDemo). - Access token. Uses the `Token <token_value>` format. This is commonly used for third party applications using the VRM API. Can be created using [/users/{idUser}/accesstokens/create](/operations/users/idUser/accesstokens/create).  ## Rate limiting Most endpoints are by default rate limited with a rolling window of max 200 requests, where every 0.33 seconds a request gets removed from the rolling window. (so on average maximum of 3 requests per second won't get rate limited). There are different types of ratelimiting in VRM. If you receive a 429 with a JSON response, you can check the Retry-After response header to check the amount of seconds you have to wait until retrying.  ## WARNING & DISCLAIMER Whilst publicly available, Victron Energy does not offer support to professional customers or end-users that implement features using the here documented functionality, except in really specific situations (i.e such as a special arrangement with a large OEM customer).  The recommended method for support on the VRM API is to use the Modifications section on Victron Community. This space is frequently visited by many people using the API, and other methods of integrating with Victron products. Direct company support is only offered on a limited basis via your Victron representative.
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Xunit;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing UsersIdUserSearch200ResponseResults
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UsersIdUserSearch200ResponseResultsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UsersIdUserSearch200ResponseResults
        //private UsersIdUserSearch200ResponseResults instance;

        public UsersIdUserSearch200ResponseResultsTests()
        {
            // TODO uncomment below to create an instance of UsersIdUserSearch200ResponseResults
            //instance = new UsersIdUserSearch200ResponseResults();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UsersIdUserSearch200ResponseResults
        /// </summary>
        [Fact]
        public void UsersIdUserSearch200ResponseResultsInstanceTest()
        {
            // TODO uncomment below to test "IsType" UsersIdUserSearch200ResponseResults
            //Assert.IsType<UsersIdUserSearch200ResponseResults>(instance);
        }

        /// <summary>
        /// Test the property 'SiteId'
        /// </summary>
        [Fact]
        public void SiteIdTest()
        {
            // TODO unit test for the property 'SiteId'
        }

        /// <summary>
        /// Test the property 'SiteIdentifier'
        /// </summary>
        [Fact]
        public void SiteIdentifierTest()
        {
            // TODO unit test for the property 'SiteIdentifier'
        }

        /// <summary>
        /// Test the property 'SiteName'
        /// </summary>
        [Fact]
        public void SiteNameTest()
        {
            // TODO unit test for the property 'SiteName'
        }

        /// <summary>
        /// Test the property 'AvatarUrl'
        /// </summary>
        [Fact]
        public void AvatarUrlTest()
        {
            // TODO unit test for the property 'AvatarUrl'
        }

        /// <summary>
        /// Test the property 'Highlight'
        /// </summary>
        [Fact]
        public void HighlightTest()
        {
            // TODO unit test for the property 'Highlight'
        }
    }
}
