// <auto-generated>
/*
 * VRM API
 *
 * ## Introduction This document provides a brief overview of some of the available endpoints and their parameters. The API is a REST API, accepting JSON as request body. You can use the try-it tool to play around with it, or use software like Postman.  ## Authentication Most endpoints require authentication, using a JWT token. This token should be placed in the `x-authorization` field in the HTTP header. There are two types of tokens. - Bearer token. Uses the `Bearer <token_value>` format. This is used when logging in to VRM, for example. Can be retrieved from [/auth/login](/operations/auth/login) or [/auth/loginAsDemo](/operations/auth/loginAsDemo). - Access token. Uses the `Token <token_value>` format. This is commonly used for third party applications using the VRM API. Can be created using [/users/{idUser}/accesstokens/create](/operations/users/idUser/accesstokens/create).  ## Rate limiting Most endpoints are by default rate limited with a rolling window of max 200 requests, where every 0.33 seconds a request gets removed from the rolling window. (so on average maximum of 3 requests per second won't get rate limited). There are different types of ratelimiting in VRM. If you receive a 429 with a JSON response, you can check the Retry-After response header to check the amount of seconds you have to wait until retrying.  ## WARNING & DISCLAIMER Whilst publicly available, Victron Energy does not offer support to professional customers or end-users that implement features using the here documented functionality, except in really specific situations (i.e such as a special arrangement with a large OEM customer).  The recommended method for support on the VRM API is to use the Modifications section on Victron Community. This space is frequently visited by many people using the API, and other methods of integrating with Victron products. Direct company support is only offered on a limited basis via your Victron representative.
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// AuthLogin200Response
    /// </summary>
    public partial class AuthLogin200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthLogin200Response" /> class.
        /// </summary>
        /// <param name="idUser">The id of the user for which the token was generated.</param>
        /// <param name="verificationMode">Which mode is used for verfying a login for this account.</param>
        /// <param name="verificationSent">Whether a verification code was sent, for 2FA.</param>
        /// <param name="token">The bearer token that was generated.</param>
        [JsonConstructor]
        public AuthLogin200Response(int idUser, string verificationMode, bool verificationSent, string? token = default)
        {
            IdUser = idUser;
            VerificationMode = verificationMode;
            VerificationSent = verificationSent;
            Token = token;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The id of the user for which the token was generated.
        /// </summary>
        /// <value>The id of the user for which the token was generated.</value>
        [JsonPropertyName("idUser")]
        public int IdUser { get; set; }

        /// <summary>
        /// Which mode is used for verfying a login for this account.
        /// </summary>
        /// <value>Which mode is used for verfying a login for this account.</value>
        [JsonPropertyName("verification_mode")]
        public string VerificationMode { get; set; }

        /// <summary>
        /// Whether a verification code was sent, for 2FA.
        /// </summary>
        /// <value>Whether a verification code was sent, for 2FA.</value>
        [JsonPropertyName("verification_sent")]
        public bool VerificationSent { get; set; }

        /// <summary>
        /// The bearer token that was generated.
        /// </summary>
        /// <value>The bearer token that was generated.</value>
        [JsonPropertyName("token")]
        public string? Token { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AuthLogin200Response {\n");
            sb.Append("  IdUser: ").Append(IdUser).Append("\n");
            sb.Append("  VerificationMode: ").Append(VerificationMode).Append("\n");
            sb.Append("  VerificationSent: ").Append(VerificationSent).Append("\n");
            sb.Append("  Token: ").Append(Token).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AuthLogin200Response" />
    /// </summary>
    public class AuthLogin200ResponseJsonConverter : JsonConverter<AuthLogin200Response>
    {
        /// <summary>
        /// Deserializes json to <see cref="AuthLogin200Response" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AuthLogin200Response Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> idUser = default;
            Option<string?> verificationMode = default;
            Option<bool?> verificationSent = default;
            Option<string?> token = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "idUser":
                            idUser = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "verification_mode":
                            verificationMode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "verification_sent":
                            verificationSent = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "token":
                            token = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!idUser.IsSet)
                throw new ArgumentException("Property is required for class AuthLogin200Response.", nameof(idUser));

            if (!verificationMode.IsSet)
                throw new ArgumentException("Property is required for class AuthLogin200Response.", nameof(verificationMode));

            if (!verificationSent.IsSet)
                throw new ArgumentException("Property is required for class AuthLogin200Response.", nameof(verificationSent));

            if (!token.IsSet)
                throw new ArgumentException("Property is required for class AuthLogin200Response.", nameof(token));

            if (idUser.IsSet && idUser.Value == null)
                throw new ArgumentNullException(nameof(idUser), "Property is not nullable for class AuthLogin200Response.");

            if (verificationMode.IsSet && verificationMode.Value == null)
                throw new ArgumentNullException(nameof(verificationMode), "Property is not nullable for class AuthLogin200Response.");

            if (verificationSent.IsSet && verificationSent.Value == null)
                throw new ArgumentNullException(nameof(verificationSent), "Property is not nullable for class AuthLogin200Response.");

            return new AuthLogin200Response(idUser.Value!.Value!, verificationMode.Value!, verificationSent.Value!.Value!, token.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="AuthLogin200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="authLogin200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AuthLogin200Response authLogin200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, authLogin200Response, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AuthLogin200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="authLogin200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AuthLogin200Response authLogin200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            if (authLogin200Response.VerificationMode == null)
                throw new ArgumentNullException(nameof(authLogin200Response.VerificationMode), "Property is required for class AuthLogin200Response.");

            writer.WriteNumber("idUser", authLogin200Response.IdUser);

            writer.WriteString("verification_mode", authLogin200Response.VerificationMode);

            writer.WriteBoolean("verification_sent", authLogin200Response.VerificationSent);

            if (authLogin200Response.Token != null)
                writer.WriteString("token", authLogin200Response.Token);
            else
                writer.WriteNull("token");
        }
    }
}
