// <auto-generated>
/*
 * VRM API
 *
 * ## Introduction This document provides a brief overview of some of the available endpoints and their parameters. The API is a REST API, accepting JSON as request body. You can use the try-it tool to play around with it, or use software like Postman.  ## Authentication Most endpoints require authentication, using a JWT token. This token should be placed in the `x-authorization` field in the HTTP header. There are two types of tokens. - Bearer token. Uses the `Bearer <token_value>` format. This is used when logging in to VRM, for example. Can be retrieved from [/auth/login](/operations/auth/login) or [/auth/loginAsDemo](/operations/auth/loginAsDemo). - Access token. Uses the `Token <token_value>` format. This is commonly used for third party applications using the VRM API. Can be created using [/users/{idUser}/accesstokens/create](/operations/users/idUser/accesstokens/create).  ## Rate limiting Most endpoints are by default rate limited with a rolling window of max 200 requests, where every 0.33 seconds a request gets removed from the rolling window. (so on average maximum of 3 requests per second won't get rate limited). There are different types of ratelimiting in VRM. If you receive a 429 with a JSON response, you can check the Retry-After response header to check the amount of seconds you have to wait until retrying.  ## WARNING & DISCLAIMER Whilst publicly available, Victron Energy does not offer support to professional customers or end-users that implement features using the here documented functionality, except in really specific situations (i.e such as a special arrangement with a large OEM customer).  The recommended method for support on the VRM API is to use the Modifications section on Victron Community. This space is frequently visited by many people using the API, and other methods of integrating with Victron products. Direct company support is only offered on a limited basis via your Victron representative.
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// InstallationsIdSiteCustomWidgetGet200Response
    /// </summary>
    public partial class InstallationsIdSiteCustomWidgetGet200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InstallationsIdSiteCustomWidgetGet200Response" /> class.
        /// </summary>
        /// <param name="success">True if the request was successful.</param>
        /// <param name="widget">Custom Widget data received successfully.</param>
        [JsonConstructor]
        public InstallationsIdSiteCustomWidgetGet200Response(Option<bool?> success = default, Option<Object?> widget = default)
        {
            SuccessOption = success;
            WidgetOption = widget;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Success
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> SuccessOption { get; private set; }

        /// <summary>
        /// True if the request was successful.
        /// </summary>
        /// <value>True if the request was successful.</value>
        [JsonPropertyName("success")]
        public bool? Success { get { return this.SuccessOption; } set { this.SuccessOption = new(value); } }

        /// <summary>
        /// Used to track the state of Widget
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> WidgetOption { get; private set; }

        /// <summary>
        /// Custom Widget data received successfully.
        /// </summary>
        /// <value>Custom Widget data received successfully.</value>
        [JsonPropertyName("widget")]
        public Object? Widget { get { return this.WidgetOption; } set { this.WidgetOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InstallationsIdSiteCustomWidgetGet200Response {\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("  Widget: ").Append(Widget).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="InstallationsIdSiteCustomWidgetGet200Response" />
    /// </summary>
    public class InstallationsIdSiteCustomWidgetGet200ResponseJsonConverter : JsonConverter<InstallationsIdSiteCustomWidgetGet200Response>
    {
        /// <summary>
        /// Deserializes json to <see cref="InstallationsIdSiteCustomWidgetGet200Response" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override InstallationsIdSiteCustomWidgetGet200Response Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> success = default;
            Option<Object?> widget = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "success":
                            success = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "widget":
                            widget = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (success.IsSet && success.Value == null)
                throw new ArgumentNullException(nameof(success), "Property is not nullable for class InstallationsIdSiteCustomWidgetGet200Response.");

            if (widget.IsSet && widget.Value == null)
                throw new ArgumentNullException(nameof(widget), "Property is not nullable for class InstallationsIdSiteCustomWidgetGet200Response.");

            return new InstallationsIdSiteCustomWidgetGet200Response(success, widget);
        }

        /// <summary>
        /// Serializes a <see cref="InstallationsIdSiteCustomWidgetGet200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="installationsIdSiteCustomWidgetGet200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, InstallationsIdSiteCustomWidgetGet200Response installationsIdSiteCustomWidgetGet200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, installationsIdSiteCustomWidgetGet200Response, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="InstallationsIdSiteCustomWidgetGet200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="installationsIdSiteCustomWidgetGet200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, InstallationsIdSiteCustomWidgetGet200Response installationsIdSiteCustomWidgetGet200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            if (installationsIdSiteCustomWidgetGet200Response.WidgetOption.IsSet && installationsIdSiteCustomWidgetGet200Response.Widget == null)
                throw new ArgumentNullException(nameof(installationsIdSiteCustomWidgetGet200Response.Widget), "Property is required for class InstallationsIdSiteCustomWidgetGet200Response.");

            if (installationsIdSiteCustomWidgetGet200Response.SuccessOption.IsSet)
                writer.WriteBoolean("success", installationsIdSiteCustomWidgetGet200Response.SuccessOption.Value!.Value);

            if (installationsIdSiteCustomWidgetGet200Response.WidgetOption.IsSet)
            {
                writer.WritePropertyName("widget");
                JsonSerializer.Serialize(writer, installationsIdSiteCustomWidgetGet200Response.Widget, jsonSerializerOptions);
            }
        }
    }
}
