// <auto-generated>
/*
 * VRM API
 *
 * ## Introduction This document provides a brief overview of some of the available endpoints and their parameters. The API is a REST API, accepting JSON as request body. You can use the try-it tool to play around with it, or use software like Postman.  ## Authentication Most endpoints require authentication, using a JWT token. This token should be placed in the `x-authorization` field in the HTTP header. There are two types of tokens. - Bearer token. Uses the `Bearer <token_value>` format. This is used when logging in to VRM, for example. Can be retrieved from [/auth/login](/operations/auth/login) or [/auth/loginAsDemo](/operations/auth/loginAsDemo). - Access token. Uses the `Token <token_value>` format. This is commonly used for third party applications using the VRM API. Can be created using [/users/{idUser}/accesstokens/create](/operations/users/idUser/accesstokens/create).  ## Rate limiting Most endpoints are by default rate limited with a rolling window of max 200 requests, where every 0.33 seconds a request gets removed from the rolling window. (so on average maximum of 3 requests per second won't get rate limited). There are different types of ratelimiting in VRM. If you receive a 429 with a JSON response, you can check the Retry-After response header to check the amount of seconds you have to wait until retrying.  ## WARNING & DISCLAIMER Whilst publicly available, Victron Energy does not offer support to professional customers or end-users that implement features using the here documented functionality, except in really specific situations (i.e such as a special arrangement with a large OEM customer).  The recommended method for support on the VRM API is to use the Modifications section on Victron Community. This space is frequently visited by many people using the API, and other methods of integrating with Victron products. Direct company support is only offered on a limited basis via your Victron representative.
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Fetched summary.
    /// </summary>
    public partial class InstallationsIdSiteWidgetsBatterySummary200ResponseRecords : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InstallationsIdSiteWidgetsBatterySummary200ResponseRecords" /> class.
        /// </summary>
        /// <param name="data">data</param>
        /// <param name="meta">Meta data per data attribute.</param>
        /// <param name="attributeOrder">Sorting order of data attributes.</param>
        [JsonConstructor]
        public InstallationsIdSiteWidgetsBatterySummary200ResponseRecords(InstallationsIdSiteWidgetsBatterySummary200ResponseRecordsData data, Dictionary<string, InstallationsIdSiteWidgetsGPS200ResponseRecordsMetaValue> meta, List<int> attributeOrder)
        {
            Data = data;
            Meta = meta;
            AttributeOrder = attributeOrder;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [JsonPropertyName("data")]
        public InstallationsIdSiteWidgetsBatterySummary200ResponseRecordsData Data { get; set; }

        /// <summary>
        /// Meta data per data attribute.
        /// </summary>
        /// <value>Meta data per data attribute.</value>
        [JsonPropertyName("meta")]
        public Dictionary<string, InstallationsIdSiteWidgetsGPS200ResponseRecordsMetaValue> Meta { get; set; }

        /// <summary>
        /// Sorting order of data attributes.
        /// </summary>
        /// <value>Sorting order of data attributes.</value>
        [JsonPropertyName("attributeOrder")]
        public List<int> AttributeOrder { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InstallationsIdSiteWidgetsBatterySummary200ResponseRecords {\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  Meta: ").Append(Meta).Append("\n");
            sb.Append("  AttributeOrder: ").Append(AttributeOrder).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="InstallationsIdSiteWidgetsBatterySummary200ResponseRecords" />
    /// </summary>
    public class InstallationsIdSiteWidgetsBatterySummary200ResponseRecordsJsonConverter : JsonConverter<InstallationsIdSiteWidgetsBatterySummary200ResponseRecords>
    {
        /// <summary>
        /// Deserializes json to <see cref="InstallationsIdSiteWidgetsBatterySummary200ResponseRecords" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override InstallationsIdSiteWidgetsBatterySummary200ResponseRecords Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<InstallationsIdSiteWidgetsBatterySummary200ResponseRecordsData?> data = default;
            Option<Dictionary<string, InstallationsIdSiteWidgetsGPS200ResponseRecordsMetaValue>?> meta = default;
            Option<List<int>?> attributeOrder = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "data":
                            data = new Option<InstallationsIdSiteWidgetsBatterySummary200ResponseRecordsData?>(JsonSerializer.Deserialize<InstallationsIdSiteWidgetsBatterySummary200ResponseRecordsData>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "meta":
                            meta = new Option<Dictionary<string, InstallationsIdSiteWidgetsGPS200ResponseRecordsMetaValue>?>(JsonSerializer.Deserialize<Dictionary<string, InstallationsIdSiteWidgetsGPS200ResponseRecordsMetaValue>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "attributeOrder":
                            attributeOrder = new Option<List<int>?>(JsonSerializer.Deserialize<List<int>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!data.IsSet)
                throw new ArgumentException("Property is required for class InstallationsIdSiteWidgetsBatterySummary200ResponseRecords.", nameof(data));

            if (!meta.IsSet)
                throw new ArgumentException("Property is required for class InstallationsIdSiteWidgetsBatterySummary200ResponseRecords.", nameof(meta));

            if (!attributeOrder.IsSet)
                throw new ArgumentException("Property is required for class InstallationsIdSiteWidgetsBatterySummary200ResponseRecords.", nameof(attributeOrder));

            if (data.IsSet && data.Value == null)
                throw new ArgumentNullException(nameof(data), "Property is not nullable for class InstallationsIdSiteWidgetsBatterySummary200ResponseRecords.");

            if (meta.IsSet && meta.Value == null)
                throw new ArgumentNullException(nameof(meta), "Property is not nullable for class InstallationsIdSiteWidgetsBatterySummary200ResponseRecords.");

            if (attributeOrder.IsSet && attributeOrder.Value == null)
                throw new ArgumentNullException(nameof(attributeOrder), "Property is not nullable for class InstallationsIdSiteWidgetsBatterySummary200ResponseRecords.");

            return new InstallationsIdSiteWidgetsBatterySummary200ResponseRecords(data.Value!, meta.Value!, attributeOrder.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="InstallationsIdSiteWidgetsBatterySummary200ResponseRecords" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="installationsIdSiteWidgetsBatterySummary200ResponseRecords"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, InstallationsIdSiteWidgetsBatterySummary200ResponseRecords installationsIdSiteWidgetsBatterySummary200ResponseRecords, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, installationsIdSiteWidgetsBatterySummary200ResponseRecords, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="InstallationsIdSiteWidgetsBatterySummary200ResponseRecords" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="installationsIdSiteWidgetsBatterySummary200ResponseRecords"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, InstallationsIdSiteWidgetsBatterySummary200ResponseRecords installationsIdSiteWidgetsBatterySummary200ResponseRecords, JsonSerializerOptions jsonSerializerOptions)
        {
            if (installationsIdSiteWidgetsBatterySummary200ResponseRecords.Data == null)
                throw new ArgumentNullException(nameof(installationsIdSiteWidgetsBatterySummary200ResponseRecords.Data), "Property is required for class InstallationsIdSiteWidgetsBatterySummary200ResponseRecords.");

            if (installationsIdSiteWidgetsBatterySummary200ResponseRecords.Meta == null)
                throw new ArgumentNullException(nameof(installationsIdSiteWidgetsBatterySummary200ResponseRecords.Meta), "Property is required for class InstallationsIdSiteWidgetsBatterySummary200ResponseRecords.");

            if (installationsIdSiteWidgetsBatterySummary200ResponseRecords.AttributeOrder == null)
                throw new ArgumentNullException(nameof(installationsIdSiteWidgetsBatterySummary200ResponseRecords.AttributeOrder), "Property is required for class InstallationsIdSiteWidgetsBatterySummary200ResponseRecords.");

            writer.WritePropertyName("data");
            JsonSerializer.Serialize(writer, installationsIdSiteWidgetsBatterySummary200ResponseRecords.Data, jsonSerializerOptions);
            writer.WritePropertyName("meta");
            JsonSerializer.Serialize(writer, installationsIdSiteWidgetsBatterySummary200ResponseRecords.Meta, jsonSerializerOptions);
            writer.WritePropertyName("attributeOrder");
            JsonSerializer.Serialize(writer, installationsIdSiteWidgetsBatterySummary200ResponseRecords.AttributeOrder, jsonSerializerOptions);
        }
    }
}
