// <auto-generated>
/*
 * VRM API
 *
 * ## Introduction This document provides a brief overview of some of the available endpoints and their parameters. The API is a REST API, accepting JSON as request body. You can use the try-it tool to play around with it, or use software like Postman.  ## Authentication Most endpoints require authentication, using a JWT token. This token should be placed in the `x-authorization` field in the HTTP header. There are two types of tokens. - Bearer token. Uses the `Bearer <token_value>` format. This is used when logging in to VRM, for example. Can be retrieved from [/auth/login](/operations/auth/login) or [/auth/loginAsDemo](/operations/auth/loginAsDemo). - Access token. Uses the `Token <token_value>` format. This is commonly used for third party applications using the VRM API. Can be created using [/users/{idUser}/accesstokens/create](/operations/users/idUser/accesstokens/create).  ## Rate limiting Most endpoints are by default rate limited with a rolling window of max 200 requests, where every 0.33 seconds a request gets removed from the rolling window. (so on average maximum of 3 requests per second won't get rate limited). There are different types of ratelimiting in VRM. If you receive a 429 with a JSON response, you can check the Retry-After response header to check the amount of seconds you have to wait until retrying.  ## WARNING & DISCLAIMER Whilst publicly available, Victron Energy does not offer support to professional customers or end-users that implement features using the here documented functionality, except in really specific situations (i.e such as a special arrangement with a large OEM customer).  The recommended method for support on the VRM API is to use the Modifications section on Victron Community. This space is frequently visited by many people using the API, and other methods of integrating with Victron products. Direct company support is only offered on a limited basis via your Victron representative.
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Log data raw value.
    /// </summary>
    public partial class InstallationsIdSiteDiagnostics200ResponseRecordsRawValue : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InstallationsIdSiteDiagnostics200ResponseRecordsRawValue" /> class.
        /// </summary>
        /// <param name="string"></param>
        /// <param name="int"></param>
        internal InstallationsIdSiteDiagnostics200ResponseRecordsRawValue(Option<string?> @string, Option<int?> @int)
        {
            StringOption = @string;
            IntOption = @int;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of String
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> StringOption { get; private set; }

        /// <summary>
        /// Gets or Sets String
        /// </summary>
        public string? String { get { return this.StringOption; } set { this.StringOption = new(value); } }

        /// <summary>
        /// Used to track the state of Int
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> IntOption { get; private set; }

        /// <summary>
        /// Gets or Sets Int
        /// </summary>
        public int? Int { get { return this.IntOption; } set { this.IntOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InstallationsIdSiteDiagnostics200ResponseRecordsRawValue {\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="InstallationsIdSiteDiagnostics200ResponseRecordsRawValue" />
    /// </summary>
    public class InstallationsIdSiteDiagnostics200ResponseRecordsRawValueJsonConverter : JsonConverter<InstallationsIdSiteDiagnostics200ResponseRecordsRawValue>
    {
        /// <summary>
        /// Deserializes json to <see cref="InstallationsIdSiteDiagnostics200ResponseRecordsRawValue" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override InstallationsIdSiteDiagnostics200ResponseRecordsRawValue Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            string? varString = default;
            int? varInt = default;

            Utf8JsonReader utf8JsonReaderAnyOf = utf8JsonReader;
            while (utf8JsonReaderAnyOf.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReaderAnyOf.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReaderAnyOf.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReaderAnyOf.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReaderAnyOf.CurrentDepth)
                    break;

                if (utf8JsonReaderAnyOf.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReaderAnyOf.CurrentDepth - 1)
                {
                    Utf8JsonReader utf8JsonReaderString = utf8JsonReader;
                    ClientUtils.TryDeserialize<string?>(ref utf8JsonReaderString, jsonSerializerOptions, out varString);

                    Utf8JsonReader utf8JsonReaderInt = utf8JsonReader;
                    ClientUtils.TryDeserialize<int?>(ref utf8JsonReaderInt, jsonSerializerOptions, out varInt);
                }
            }

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        default:
                            break;
                    }
                }
            }

            Option<string?> varStringParsedValue = varString == null
                ? default
                : new Option<string?>(varString);
            Option<int?> varIntParsedValue = varInt == null
                ? default
                : new Option<int?>(varInt);

            return new InstallationsIdSiteDiagnostics200ResponseRecordsRawValue(varStringParsedValue, varIntParsedValue);
        }

        /// <summary>
        /// Serializes a <see cref="InstallationsIdSiteDiagnostics200ResponseRecordsRawValue" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="installationsIdSiteDiagnostics200ResponseRecordsRawValue"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, InstallationsIdSiteDiagnostics200ResponseRecordsRawValue installationsIdSiteDiagnostics200ResponseRecordsRawValue, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            if (installationsIdSiteDiagnostics200ResponseRecordsRawValue.StringOption.IsSet && installationsIdSiteDiagnostics200ResponseRecordsRawValue.StringOption.Value != null)
                writer.WriteString("vmc", installationsIdSiteDiagnostics200ResponseRecordsRawValue.StringOption.Value);

            if (installationsIdSiteDiagnostics200ResponseRecordsRawValue.IntOption.IsSet && installationsIdSiteDiagnostics200ResponseRecordsRawValue.IntOption.Value != null)
                writer.WriteNumber("rawValue", installationsIdSiteDiagnostics200ResponseRecordsRawValue.IntOption.Value.Value);

            WriteProperties(writer, installationsIdSiteDiagnostics200ResponseRecordsRawValue, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="InstallationsIdSiteDiagnostics200ResponseRecordsRawValue" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="installationsIdSiteDiagnostics200ResponseRecordsRawValue"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, InstallationsIdSiteDiagnostics200ResponseRecordsRawValue installationsIdSiteDiagnostics200ResponseRecordsRawValue, JsonSerializerOptions jsonSerializerOptions)
        {

        }
    }
}
