// <auto-generated>
/*
 * VRM API
 *
 * ## Introduction This document provides a brief overview of some of the available endpoints and their parameters. The API is a REST API, accepting JSON as request body. You can use the try-it tool to play around with it, or use software like Postman.  ## Authentication Most endpoints require authentication, using a JWT token. This token should be placed in the `x-authorization` field in the HTTP header. There are two types of tokens. - Bearer token. Uses the `Bearer <token_value>` format. This is used when logging in to VRM, for example. Can be retrieved from [/auth/login](/operations/auth/login) or [/auth/loginAsDemo](/operations/auth/loginAsDemo). - Access token. Uses the `Token <token_value>` format. This is commonly used for third party applications using the VRM API. Can be created using [/users/{idUser}/accesstokens/create](/operations/users/idUser/accesstokens/create).  ## Rate limiting Most endpoints are by default rate limited with a rolling window of max 200 requests, where every 0.33 seconds a request gets removed from the rolling window. (so on average maximum of 3 requests per second won't get rate limited). There are different types of ratelimiting in VRM. If you receive a 429 with a JSON response, you can check the Retry-After response header to check the amount of seconds you have to wait until retrying.  ## WARNING & DISCLAIMER Whilst publicly available, Victron Energy does not offer support to professional customers or end-users that implement features using the here documented functionality, except in really specific situations (i.e such as a special arrangement with a large OEM customer).  The recommended method for support on the VRM API is to use the Modifications section on Victron Community. This space is frequently visited by many people using the API, and other methods of integrating with Victron products. Direct company support is only offered on a limited basis via your Victron representative.
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Totals and percentages.
    /// </summary>
    public partial class InstallationsIdSiteOverallstats200ResponseRecordsYear : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InstallationsIdSiteOverallstats200ResponseRecordsYear" /> class.
        /// </summary>
        /// <param name="totals">Total for each data attribute.</param>
        /// <param name="percentages">Percentage for each data attribute.</param>
        [JsonConstructor]
        public InstallationsIdSiteOverallstats200ResponseRecordsYear(Dictionary<string, InstallationsIdSiteStats200ResponseTotalsOneOfValue> totals, Dictionary<string, int> percentages)
        {
            Totals = totals;
            Percentages = percentages;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Total for each data attribute.
        /// </summary>
        /// <value>Total for each data attribute.</value>
        [JsonPropertyName("totals")]
        public Dictionary<string, InstallationsIdSiteStats200ResponseTotalsOneOfValue> Totals { get; set; }

        /// <summary>
        /// Percentage for each data attribute.
        /// </summary>
        /// <value>Percentage for each data attribute.</value>
        [JsonPropertyName("percentages")]
        public Dictionary<string, int> Percentages { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InstallationsIdSiteOverallstats200ResponseRecordsYear {\n");
            sb.Append("  Totals: ").Append(Totals).Append("\n");
            sb.Append("  Percentages: ").Append(Percentages).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="InstallationsIdSiteOverallstats200ResponseRecordsYear" />
    /// </summary>
    public class InstallationsIdSiteOverallstats200ResponseRecordsYearJsonConverter : JsonConverter<InstallationsIdSiteOverallstats200ResponseRecordsYear>
    {
        /// <summary>
        /// Deserializes json to <see cref="InstallationsIdSiteOverallstats200ResponseRecordsYear" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override InstallationsIdSiteOverallstats200ResponseRecordsYear Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Dictionary<string, InstallationsIdSiteStats200ResponseTotalsOneOfValue>?> totals = default;
            Option<Dictionary<string, int>?> percentages = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "totals":
                            totals = new Option<Dictionary<string, InstallationsIdSiteStats200ResponseTotalsOneOfValue>?>(JsonSerializer.Deserialize<Dictionary<string, InstallationsIdSiteStats200ResponseTotalsOneOfValue>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "percentages":
                            percentages = new Option<Dictionary<string, int>?>(JsonSerializer.Deserialize<Dictionary<string, int>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!totals.IsSet)
                throw new ArgumentException("Property is required for class InstallationsIdSiteOverallstats200ResponseRecordsYear.", nameof(totals));

            if (!percentages.IsSet)
                throw new ArgumentException("Property is required for class InstallationsIdSiteOverallstats200ResponseRecordsYear.", nameof(percentages));

            if (totals.IsSet && totals.Value == null)
                throw new ArgumentNullException(nameof(totals), "Property is not nullable for class InstallationsIdSiteOverallstats200ResponseRecordsYear.");

            if (percentages.IsSet && percentages.Value == null)
                throw new ArgumentNullException(nameof(percentages), "Property is not nullable for class InstallationsIdSiteOverallstats200ResponseRecordsYear.");

            return new InstallationsIdSiteOverallstats200ResponseRecordsYear(totals.Value!, percentages.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="InstallationsIdSiteOverallstats200ResponseRecordsYear" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="installationsIdSiteOverallstats200ResponseRecordsYear"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, InstallationsIdSiteOverallstats200ResponseRecordsYear installationsIdSiteOverallstats200ResponseRecordsYear, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, installationsIdSiteOverallstats200ResponseRecordsYear, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="InstallationsIdSiteOverallstats200ResponseRecordsYear" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="installationsIdSiteOverallstats200ResponseRecordsYear"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, InstallationsIdSiteOverallstats200ResponseRecordsYear installationsIdSiteOverallstats200ResponseRecordsYear, JsonSerializerOptions jsonSerializerOptions)
        {
            if (installationsIdSiteOverallstats200ResponseRecordsYear.Totals == null)
                throw new ArgumentNullException(nameof(installationsIdSiteOverallstats200ResponseRecordsYear.Totals), "Property is required for class InstallationsIdSiteOverallstats200ResponseRecordsYear.");

            if (installationsIdSiteOverallstats200ResponseRecordsYear.Percentages == null)
                throw new ArgumentNullException(nameof(installationsIdSiteOverallstats200ResponseRecordsYear.Percentages), "Property is required for class InstallationsIdSiteOverallstats200ResponseRecordsYear.");

            writer.WritePropertyName("totals");
            JsonSerializer.Serialize(writer, installationsIdSiteOverallstats200ResponseRecordsYear.Totals, jsonSerializerOptions);
            writer.WritePropertyName("percentages");
            JsonSerializer.Serialize(writer, installationsIdSiteOverallstats200ResponseRecordsYear.Percentages, jsonSerializerOptions);
        }
    }
}
