// <auto-generated>
/*
 * VRM API
 *
 * ## Introduction This document provides a brief overview of some of the available endpoints and their parameters. The API is a REST API, accepting JSON as request body. You can use the try-it tool to play around with it, or use software like Postman.  ## Authentication Most endpoints require authentication, using a JWT token. This token should be placed in the `x-authorization` field in the HTTP header. There are two types of tokens. - Bearer token. Uses the `Bearer <token_value>` format. This is used when logging in to VRM, for example. Can be retrieved from [/auth/login](/operations/auth/login) or [/auth/loginAsDemo](/operations/auth/loginAsDemo). - Access token. Uses the `Token <token_value>` format. This is commonly used for third party applications using the VRM API. Can be created using [/users/{idUser}/accesstokens/create](/operations/users/idUser/accesstokens/create).  ## Rate limiting Most endpoints are by default rate limited with a rolling window of max 200 requests, where every 0.33 seconds a request gets removed from the rolling window. (so on average maximum of 3 requests per second won't get rate limited). There are different types of ratelimiting in VRM. If you receive a 429 with a JSON response, you can check the Retry-After response header to check the amount of seconds you have to wait until retrying.  ## WARNING & DISCLAIMER Whilst publicly available, Victron Energy does not offer support to professional customers or end-users that implement features using the here documented functionality, except in really specific situations (i.e such as a special arrangement with a large OEM customer).  The recommended method for support on the VRM API is to use the Modifications section on Victron Community. This space is frequently visited by many people using the API, and other methods of integrating with Victron products. Direct company support is only offered on a limited basis via your Victron representative.
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Units per phase.
    /// </summary>
    public partial class InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerVidDevicesPerPhase : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerVidDevicesPerPhase" /> class.
        /// </summary>
        /// <param name="l1">l1</param>
        /// <param name="l2">l2</param>
        /// <param name="l3">l3</param>
        [JsonConstructor]
        public InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerVidDevicesPerPhase(int l1, int l2, int l3)
        {
            L1 = l1;
            L2 = l2;
            L3 = l3;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets L1
        /// </summary>
        [JsonPropertyName("L1")]
        public int L1 { get; set; }

        /// <summary>
        /// Gets or Sets L2
        /// </summary>
        [JsonPropertyName("L2")]
        public int L2 { get; set; }

        /// <summary>
        /// Gets or Sets L3
        /// </summary>
        [JsonPropertyName("L3")]
        public int L3 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerVidDevicesPerPhase {\n");
            sb.Append("  L1: ").Append(L1).Append("\n");
            sb.Append("  L2: ").Append(L2).Append("\n");
            sb.Append("  L3: ").Append(L3).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerVidDevicesPerPhase" />
    /// </summary>
    public class InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerVidDevicesPerPhaseJsonConverter : JsonConverter<InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerVidDevicesPerPhase>
    {
        /// <summary>
        /// Deserializes json to <see cref="InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerVidDevicesPerPhase" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerVidDevicesPerPhase Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> l1 = default;
            Option<int?> l2 = default;
            Option<int?> l3 = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "L1":
                            l1 = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "L2":
                            l2 = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "L3":
                            l3 = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!l1.IsSet)
                throw new ArgumentException("Property is required for class InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerVidDevicesPerPhase.", nameof(l1));

            if (!l2.IsSet)
                throw new ArgumentException("Property is required for class InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerVidDevicesPerPhase.", nameof(l2));

            if (!l3.IsSet)
                throw new ArgumentException("Property is required for class InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerVidDevicesPerPhase.", nameof(l3));

            if (l1.IsSet && l1.Value == null)
                throw new ArgumentNullException(nameof(l1), "Property is not nullable for class InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerVidDevicesPerPhase.");

            if (l2.IsSet && l2.Value == null)
                throw new ArgumentNullException(nameof(l2), "Property is not nullable for class InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerVidDevicesPerPhase.");

            if (l3.IsSet && l3.Value == null)
                throw new ArgumentNullException(nameof(l3), "Property is not nullable for class InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerVidDevicesPerPhase.");

            return new InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerVidDevicesPerPhase(l1.Value!.Value!, l2.Value!.Value!, l3.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerVidDevicesPerPhase" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="installationsIdSiteSystemOverview200ResponseRecordsDevicesInnerVidDevicesPerPhase"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerVidDevicesPerPhase installationsIdSiteSystemOverview200ResponseRecordsDevicesInnerVidDevicesPerPhase, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, installationsIdSiteSystemOverview200ResponseRecordsDevicesInnerVidDevicesPerPhase, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerVidDevicesPerPhase" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="installationsIdSiteSystemOverview200ResponseRecordsDevicesInnerVidDevicesPerPhase"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerVidDevicesPerPhase installationsIdSiteSystemOverview200ResponseRecordsDevicesInnerVidDevicesPerPhase, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("L1", installationsIdSiteSystemOverview200ResponseRecordsDevicesInnerVidDevicesPerPhase.L1);

            writer.WriteNumber("L2", installationsIdSiteSystemOverview200ResponseRecordsDevicesInnerVidDevicesPerPhase.L2);

            writer.WriteNumber("L3", installationsIdSiteSystemOverview200ResponseRecordsDevicesInnerVidDevicesPerPhase.L3);
        }
    }
}
