// <auto-generated>
/*
 * VRM API
 *
 * ## Introduction This document provides a brief overview of some of the available endpoints and their parameters. The API is a REST API, accepting JSON as request body. You can use the try-it tool to play around with it, or use software like Postman.  ## Authentication Most endpoints require authentication, using a JWT token. This token should be placed in the `x-authorization` field in the HTTP header. There are two types of tokens. - Bearer token. Uses the `Bearer <token_value>` format. This is used when logging in to VRM, for example. Can be retrieved from [/auth/login](/operations/auth/login) or [/auth/loginAsDemo](/operations/auth/loginAsDemo). - Access token. Uses the `Token <token_value>` format. This is commonly used for third party applications using the VRM API. Can be created using [/users/{idUser}/accesstokens/create](/operations/users/idUser/accesstokens/create).  ## Rate limiting Most endpoints are by default rate limited with a rolling window of max 200 requests, where every 0.33 seconds a request gets removed from the rolling window. (so on average maximum of 3 requests per second won't get rate limited). There are different types of ratelimiting in VRM. If you receive a 429 with a JSON response, you can check the Retry-After response header to check the amount of seconds you have to wait until retrying.  ## WARNING & DISCLAIMER Whilst publicly available, Victron Energy does not offer support to professional customers or end-users that implement features using the here documented functionality, except in really specific situations (i.e such as a special arrangement with a large OEM customer).  The recommended method for support on the VRM API is to use the Modifications section on Victron Community. This space is frequently visited by many people using the API, and other methods of integrating with Victron products. Direct company support is only offered on a limited basis via your Victron representative.
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// InstallationOverviewDownloadRequest
    /// </summary>
    public partial class InstallationOverviewDownloadRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InstallationOverviewDownloadRequest" /> class.
        /// </summary>
        /// <param name="columns">Configuration of the columns to include in the overview.</param>
        /// <param name="siteIds">List of site IDs to include in the overview.</param>
        /// <param name="onlyVisible">Whether only visible items should be included.</param>
        /// <param name="jsonResponse">Whether the response should be in JSON format. If false, an XLSX file will be returned.</param>
        [JsonConstructor]
        public InstallationOverviewDownloadRequest(Dictionary<string, InstallationOverviewDownloadRequestColumnsValue> columns, List<int> siteIds, bool onlyVisible, bool jsonResponse)
        {
            Columns = columns;
            SiteIds = siteIds;
            OnlyVisible = onlyVisible;
            JsonResponse = jsonResponse;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Configuration of the columns to include in the overview.
        /// </summary>
        /// <value>Configuration of the columns to include in the overview.</value>
        [JsonPropertyName("columns")]
        public Dictionary<string, InstallationOverviewDownloadRequestColumnsValue> Columns { get; set; }

        /// <summary>
        /// List of site IDs to include in the overview.
        /// </summary>
        /// <value>List of site IDs to include in the overview.</value>
        [JsonPropertyName("siteIds")]
        public List<int> SiteIds { get; set; }

        /// <summary>
        /// Whether only visible items should be included.
        /// </summary>
        /// <value>Whether only visible items should be included.</value>
        [JsonPropertyName("onlyVisible")]
        public bool OnlyVisible { get; set; }

        /// <summary>
        /// Whether the response should be in JSON format. If false, an XLSX file will be returned.
        /// </summary>
        /// <value>Whether the response should be in JSON format. If false, an XLSX file will be returned.</value>
        [JsonPropertyName("jsonResponse")]
        public bool JsonResponse { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InstallationOverviewDownloadRequest {\n");
            sb.Append("  Columns: ").Append(Columns).Append("\n");
            sb.Append("  SiteIds: ").Append(SiteIds).Append("\n");
            sb.Append("  OnlyVisible: ").Append(OnlyVisible).Append("\n");
            sb.Append("  JsonResponse: ").Append(JsonResponse).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="InstallationOverviewDownloadRequest" />
    /// </summary>
    public class InstallationOverviewDownloadRequestJsonConverter : JsonConverter<InstallationOverviewDownloadRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="InstallationOverviewDownloadRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override InstallationOverviewDownloadRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Dictionary<string, InstallationOverviewDownloadRequestColumnsValue>?> columns = default;
            Option<List<int>?> siteIds = default;
            Option<bool?> onlyVisible = default;
            Option<bool?> jsonResponse = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "columns":
                            columns = new Option<Dictionary<string, InstallationOverviewDownloadRequestColumnsValue>?>(JsonSerializer.Deserialize<Dictionary<string, InstallationOverviewDownloadRequestColumnsValue>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "siteIds":
                            siteIds = new Option<List<int>?>(JsonSerializer.Deserialize<List<int>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "onlyVisible":
                            onlyVisible = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "jsonResponse":
                            jsonResponse = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!columns.IsSet)
                throw new ArgumentException("Property is required for class InstallationOverviewDownloadRequest.", nameof(columns));

            if (!siteIds.IsSet)
                throw new ArgumentException("Property is required for class InstallationOverviewDownloadRequest.", nameof(siteIds));

            if (!onlyVisible.IsSet)
                throw new ArgumentException("Property is required for class InstallationOverviewDownloadRequest.", nameof(onlyVisible));

            if (!jsonResponse.IsSet)
                throw new ArgumentException("Property is required for class InstallationOverviewDownloadRequest.", nameof(jsonResponse));

            if (columns.IsSet && columns.Value == null)
                throw new ArgumentNullException(nameof(columns), "Property is not nullable for class InstallationOverviewDownloadRequest.");

            if (siteIds.IsSet && siteIds.Value == null)
                throw new ArgumentNullException(nameof(siteIds), "Property is not nullable for class InstallationOverviewDownloadRequest.");

            if (onlyVisible.IsSet && onlyVisible.Value == null)
                throw new ArgumentNullException(nameof(onlyVisible), "Property is not nullable for class InstallationOverviewDownloadRequest.");

            if (jsonResponse.IsSet && jsonResponse.Value == null)
                throw new ArgumentNullException(nameof(jsonResponse), "Property is not nullable for class InstallationOverviewDownloadRequest.");

            return new InstallationOverviewDownloadRequest(columns.Value!, siteIds.Value!, onlyVisible.Value!.Value!, jsonResponse.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="InstallationOverviewDownloadRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="installationOverviewDownloadRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, InstallationOverviewDownloadRequest installationOverviewDownloadRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, installationOverviewDownloadRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="InstallationOverviewDownloadRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="installationOverviewDownloadRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, InstallationOverviewDownloadRequest installationOverviewDownloadRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (installationOverviewDownloadRequest.Columns == null)
                throw new ArgumentNullException(nameof(installationOverviewDownloadRequest.Columns), "Property is required for class InstallationOverviewDownloadRequest.");

            if (installationOverviewDownloadRequest.SiteIds == null)
                throw new ArgumentNullException(nameof(installationOverviewDownloadRequest.SiteIds), "Property is required for class InstallationOverviewDownloadRequest.");

            writer.WritePropertyName("columns");
            JsonSerializer.Serialize(writer, installationOverviewDownloadRequest.Columns, jsonSerializerOptions);
            writer.WritePropertyName("siteIds");
            JsonSerializer.Serialize(writer, installationOverviewDownloadRequest.SiteIds, jsonSerializerOptions);
            writer.WriteBoolean("onlyVisible", installationOverviewDownloadRequest.OnlyVisible);

            writer.WriteBoolean("jsonResponse", installationOverviewDownloadRequest.JsonResponse);
        }
    }
}
