// <auto-generated>
/*
 * VRM API
 *
 * ## Introduction This document provides a brief overview of some of the available endpoints and their parameters. The API is a REST API, accepting JSON as request body. You can use the try-it tool to play around with it, or use software like Postman.  ## Authentication Most endpoints require authentication, using a JWT token. This token should be placed in the `x-authorization` field in the HTTP header. There are two types of tokens. - Bearer token. Uses the `Bearer <token_value>` format. This is used when logging in to VRM, for example. Can be retrieved from [/auth/login](/operations/auth/login) or [/auth/loginAsDemo](/operations/auth/loginAsDemo). - Access token. Uses the `Token <token_value>` format. This is commonly used for third party applications using the VRM API. Can be created using [/users/{idUser}/accesstokens/create](/operations/users/idUser/accesstokens/create).  ## Rate limiting Most endpoints are by default rate limited with a rolling window of max 200 requests, where every 0.33 seconds a request gets removed from the rolling window. (so on average maximum of 3 requests per second won't get rate limited). There are different types of ratelimiting in VRM. If you receive a 429 with a JSON response, you can check the Retry-After response header to check the amount of seconds you have to wait until retrying.  ## WARNING & DISCLAIMER Whilst publicly available, Victron Energy does not offer support to professional customers or end-users that implement features using the here documented functionality, except in really specific situations (i.e such as a special arrangement with a large OEM customer).  The recommended method for support on the VRM API is to use the Modifications section on Victron Community. This space is frequently visited by many people using the API, and other methods of integrating with Victron products. Direct company support is only offered on a limited basis via your Victron representative.
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// InstallationOverviewDownloadRequestColumnsValue
    /// </summary>
    public partial class InstallationOverviewDownloadRequestColumnsValue : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InstallationOverviewDownloadRequestColumnsValue" /> class.
        /// </summary>
        /// <param name="header">The header text for the column.</param>
        /// <param name="enabled">Whether the column is enabled.</param>
        /// <param name="hide">Whether the column is hidden (optional).</param>
        [JsonConstructor]
        public InstallationOverviewDownloadRequestColumnsValue(Option<string?> header = default, Option<bool?> enabled = default, Option<bool?> hide = default)
        {
            HeaderOption = header;
            EnabledOption = enabled;
            HideOption = hide;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Header
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> HeaderOption { get; private set; }

        /// <summary>
        /// The header text for the column.
        /// </summary>
        /// <value>The header text for the column.</value>
        [JsonPropertyName("header")]
        public string? Header { get { return this.HeaderOption; } set { this.HeaderOption = new(value); } }

        /// <summary>
        /// Used to track the state of Enabled
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> EnabledOption { get; private set; }

        /// <summary>
        /// Whether the column is enabled.
        /// </summary>
        /// <value>Whether the column is enabled.</value>
        [JsonPropertyName("enabled")]
        public bool? Enabled { get { return this.EnabledOption; } set { this.EnabledOption = new(value); } }

        /// <summary>
        /// Used to track the state of Hide
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> HideOption { get; private set; }

        /// <summary>
        /// Whether the column is hidden (optional).
        /// </summary>
        /// <value>Whether the column is hidden (optional).</value>
        [JsonPropertyName("hide")]
        public bool? Hide { get { return this.HideOption; } set { this.HideOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InstallationOverviewDownloadRequestColumnsValue {\n");
            sb.Append("  Header: ").Append(Header).Append("\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  Hide: ").Append(Hide).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="InstallationOverviewDownloadRequestColumnsValue" />
    /// </summary>
    public class InstallationOverviewDownloadRequestColumnsValueJsonConverter : JsonConverter<InstallationOverviewDownloadRequestColumnsValue>
    {
        /// <summary>
        /// Deserializes json to <see cref="InstallationOverviewDownloadRequestColumnsValue" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override InstallationOverviewDownloadRequestColumnsValue Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> header = default;
            Option<bool?> enabled = default;
            Option<bool?> hide = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "header":
                            header = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "enabled":
                            enabled = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "hide":
                            hide = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (header.IsSet && header.Value == null)
                throw new ArgumentNullException(nameof(header), "Property is not nullable for class InstallationOverviewDownloadRequestColumnsValue.");

            if (enabled.IsSet && enabled.Value == null)
                throw new ArgumentNullException(nameof(enabled), "Property is not nullable for class InstallationOverviewDownloadRequestColumnsValue.");

            if (hide.IsSet && hide.Value == null)
                throw new ArgumentNullException(nameof(hide), "Property is not nullable for class InstallationOverviewDownloadRequestColumnsValue.");

            return new InstallationOverviewDownloadRequestColumnsValue(header, enabled, hide);
        }

        /// <summary>
        /// Serializes a <see cref="InstallationOverviewDownloadRequestColumnsValue" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="installationOverviewDownloadRequestColumnsValue"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, InstallationOverviewDownloadRequestColumnsValue installationOverviewDownloadRequestColumnsValue, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, installationOverviewDownloadRequestColumnsValue, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="InstallationOverviewDownloadRequestColumnsValue" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="installationOverviewDownloadRequestColumnsValue"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, InstallationOverviewDownloadRequestColumnsValue installationOverviewDownloadRequestColumnsValue, JsonSerializerOptions jsonSerializerOptions)
        {
            if (installationOverviewDownloadRequestColumnsValue.HeaderOption.IsSet && installationOverviewDownloadRequestColumnsValue.Header == null)
                throw new ArgumentNullException(nameof(installationOverviewDownloadRequestColumnsValue.Header), "Property is required for class InstallationOverviewDownloadRequestColumnsValue.");

            if (installationOverviewDownloadRequestColumnsValue.HeaderOption.IsSet)
                writer.WriteString("header", installationOverviewDownloadRequestColumnsValue.Header);

            if (installationOverviewDownloadRequestColumnsValue.EnabledOption.IsSet)
                writer.WriteBoolean("enabled", installationOverviewDownloadRequestColumnsValue.EnabledOption.Value!.Value);

            if (installationOverviewDownloadRequestColumnsValue.HideOption.IsSet)
                writer.WriteBoolean("hide", installationOverviewDownloadRequestColumnsValue.HideOption.Value!.Value);
        }
    }
}
