// <auto-generated>
/*
 * VRM API
 *
 * ## Introduction This document provides a brief overview of some of the available endpoints and their parameters. The API is a REST API, accepting JSON as request body. You can use the try-it tool to play around with it, or use software like Postman.  ## Authentication Most endpoints require authentication, using a JWT token. This token should be placed in the `x-authorization` field in the HTTP header. There are two types of tokens. - Bearer token. Uses the `Bearer <token_value>` format. This is used when logging in to VRM, for example. Can be retrieved from [/auth/login](/operations/auth/login) or [/auth/loginAsDemo](/operations/auth/loginAsDemo). - Access token. Uses the `Token <token_value>` format. This is commonly used for third party applications using the VRM API. Can be created using [/users/{idUser}/accesstokens/create](/operations/users/idUser/accesstokens/create).  ## Rate limiting Most endpoints are by default rate limited with a rolling window of max 200 requests, where every 0.33 seconds a request gets removed from the rolling window. (so on average maximum of 3 requests per second won't get rate limited). There are different types of ratelimiting in VRM. If you receive a 429 with a JSON response, you can check the Retry-After response header to check the amount of seconds you have to wait until retrying.  ## WARNING & DISCLAIMER Whilst publicly available, Victron Energy does not offer support to professional customers or end-users that implement features using the here documented functionality, except in really specific situations (i.e such as a special arrangement with a large OEM customer).  The recommended method for support on the VRM API is to use the Modifications section on Victron Community. This space is frequently visited by many people using the API, and other methods of integrating with Victron products. Direct company support is only offered on a limited basis via your Victron representative.
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// InstallationsIdSiteAlarmsPutRequest
    /// </summary>
    public partial class InstallationsIdSiteAlarmsPutRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InstallationsIdSiteAlarmsPutRequest" /> class.
        /// </summary>
        /// <param name="idDataAttribute">idDataAttribute</param>
        /// <param name="instance">instance</param>
        /// <param name="alarmEnabled">alarmEnabled</param>
        /// <param name="notifyAfterSeconds">notifyAfterSeconds</param>
        /// <param name="highAlarm">highAlarm</param>
        /// <param name="highAlarmHysteresis">highAlarmHysteresis</param>
        /// <param name="lowAlarm">lowAlarm</param>
        /// <param name="lowAlarmHysteresis">lowAlarmHysteresis</param>
        /// <param name="enumValues">enumValues</param>
        [JsonConstructor]
        public InstallationsIdSiteAlarmsPutRequest(Option<decimal?> idDataAttribute = default, Option<decimal?> instance = default, Option<decimal?> alarmEnabled = default, Option<decimal?> notifyAfterSeconds = default, Option<decimal?> highAlarm = default, Option<decimal?> highAlarmHysteresis = default, Option<decimal?> lowAlarm = default, Option<decimal?> lowAlarmHysteresis = default, Option<List<string>?> enumValues = default)
        {
            IdDataAttributeOption = idDataAttribute;
            InstanceOption = instance;
            AlarmEnabledOption = alarmEnabled;
            NotifyAfterSecondsOption = notifyAfterSeconds;
            HighAlarmOption = highAlarm;
            HighAlarmHysteresisOption = highAlarmHysteresis;
            LowAlarmOption = lowAlarm;
            LowAlarmHysteresisOption = lowAlarmHysteresis;
            EnumValuesOption = enumValues;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of IdDataAttribute
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> IdDataAttributeOption { get; private set; }

        /// <summary>
        /// Gets or Sets IdDataAttribute
        /// </summary>
        /* <example>630</example> */
        [JsonPropertyName("idDataAttribute")]
        public decimal? IdDataAttribute { get { return this.IdDataAttributeOption; } set { this.IdDataAttributeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Instance
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> InstanceOption { get; private set; }

        /// <summary>
        /// Gets or Sets Instance
        /// </summary>
        /* <example>0</example> */
        [JsonPropertyName("instance")]
        public decimal? Instance { get { return this.InstanceOption; } set { this.InstanceOption = new(value); } }

        /// <summary>
        /// Used to track the state of AlarmEnabled
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> AlarmEnabledOption { get; private set; }

        /// <summary>
        /// Gets or Sets AlarmEnabled
        /// </summary>
        /* <example>1</example> */
        [JsonPropertyName("AlarmEnabled")]
        public decimal? AlarmEnabled { get { return this.AlarmEnabledOption; } set { this.AlarmEnabledOption = new(value); } }

        /// <summary>
        /// Used to track the state of NotifyAfterSeconds
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> NotifyAfterSecondsOption { get; private set; }

        /// <summary>
        /// Gets or Sets NotifyAfterSeconds
        /// </summary>
        /* <example>60</example> */
        [JsonPropertyName("NotifyAfterSeconds")]
        public decimal? NotifyAfterSeconds { get { return this.NotifyAfterSecondsOption; } set { this.NotifyAfterSecondsOption = new(value); } }

        /// <summary>
        /// Used to track the state of HighAlarm
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> HighAlarmOption { get; private set; }

        /// <summary>
        /// Gets or Sets HighAlarm
        /// </summary>
        /* <example>2</example> */
        [JsonPropertyName("highAlarm")]
        public decimal? HighAlarm { get { return this.HighAlarmOption; } set { this.HighAlarmOption = new(value); } }

        /// <summary>
        /// Used to track the state of HighAlarmHysteresis
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> HighAlarmHysteresisOption { get; private set; }

        /// <summary>
        /// Gets or Sets HighAlarmHysteresis
        /// </summary>
        /* <example>2</example> */
        [JsonPropertyName("highAlarmHysteresis")]
        public decimal? HighAlarmHysteresis { get { return this.HighAlarmHysteresisOption; } set { this.HighAlarmHysteresisOption = new(value); } }

        /// <summary>
        /// Used to track the state of LowAlarm
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> LowAlarmOption { get; private set; }

        /// <summary>
        /// Gets or Sets LowAlarm
        /// </summary>
        /* <example>0</example> */
        [JsonPropertyName("lowAlarm")]
        public decimal? LowAlarm { get { return this.LowAlarmOption; } set { this.LowAlarmOption = new(value); } }

        /// <summary>
        /// Used to track the state of LowAlarmHysteresis
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> LowAlarmHysteresisOption { get; private set; }

        /// <summary>
        /// Gets or Sets LowAlarmHysteresis
        /// </summary>
        /* <example>0.2</example> */
        [JsonPropertyName("lowAlarmHysteresis")]
        public decimal? LowAlarmHysteresis { get { return this.LowAlarmHysteresisOption; } set { this.LowAlarmHysteresisOption = new(value); } }

        /// <summary>
        /// Used to track the state of EnumValues
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> EnumValuesOption { get; private set; }

        /// <summary>
        /// Gets or Sets EnumValues
        /// </summary>
        /* <example>[0,4,6]</example> */
        [JsonPropertyName("enumValues")]
        public List<string>? EnumValues { get { return this.EnumValuesOption; } set { this.EnumValuesOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InstallationsIdSiteAlarmsPutRequest {\n");
            sb.Append("  IdDataAttribute: ").Append(IdDataAttribute).Append("\n");
            sb.Append("  Instance: ").Append(Instance).Append("\n");
            sb.Append("  AlarmEnabled: ").Append(AlarmEnabled).Append("\n");
            sb.Append("  NotifyAfterSeconds: ").Append(NotifyAfterSeconds).Append("\n");
            sb.Append("  HighAlarm: ").Append(HighAlarm).Append("\n");
            sb.Append("  HighAlarmHysteresis: ").Append(HighAlarmHysteresis).Append("\n");
            sb.Append("  LowAlarm: ").Append(LowAlarm).Append("\n");
            sb.Append("  LowAlarmHysteresis: ").Append(LowAlarmHysteresis).Append("\n");
            sb.Append("  EnumValues: ").Append(EnumValues).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="InstallationsIdSiteAlarmsPutRequest" />
    /// </summary>
    public class InstallationsIdSiteAlarmsPutRequestJsonConverter : JsonConverter<InstallationsIdSiteAlarmsPutRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="InstallationsIdSiteAlarmsPutRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override InstallationsIdSiteAlarmsPutRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<decimal?> idDataAttribute = default;
            Option<decimal?> instance = default;
            Option<decimal?> alarmEnabled = default;
            Option<decimal?> notifyAfterSeconds = default;
            Option<decimal?> highAlarm = default;
            Option<decimal?> highAlarmHysteresis = default;
            Option<decimal?> lowAlarm = default;
            Option<decimal?> lowAlarmHysteresis = default;
            Option<List<string>?> enumValues = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "idDataAttribute":
                            idDataAttribute = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "instance":
                            instance = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "AlarmEnabled":
                            alarmEnabled = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "NotifyAfterSeconds":
                            notifyAfterSeconds = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "highAlarm":
                            highAlarm = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "highAlarmHysteresis":
                            highAlarmHysteresis = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "lowAlarm":
                            lowAlarm = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "lowAlarmHysteresis":
                            lowAlarmHysteresis = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "enumValues":
                            enumValues = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (idDataAttribute.IsSet && idDataAttribute.Value == null)
                throw new ArgumentNullException(nameof(idDataAttribute), "Property is not nullable for class InstallationsIdSiteAlarmsPutRequest.");

            if (instance.IsSet && instance.Value == null)
                throw new ArgumentNullException(nameof(instance), "Property is not nullable for class InstallationsIdSiteAlarmsPutRequest.");

            if (alarmEnabled.IsSet && alarmEnabled.Value == null)
                throw new ArgumentNullException(nameof(alarmEnabled), "Property is not nullable for class InstallationsIdSiteAlarmsPutRequest.");

            if (notifyAfterSeconds.IsSet && notifyAfterSeconds.Value == null)
                throw new ArgumentNullException(nameof(notifyAfterSeconds), "Property is not nullable for class InstallationsIdSiteAlarmsPutRequest.");

            if (highAlarm.IsSet && highAlarm.Value == null)
                throw new ArgumentNullException(nameof(highAlarm), "Property is not nullable for class InstallationsIdSiteAlarmsPutRequest.");

            if (highAlarmHysteresis.IsSet && highAlarmHysteresis.Value == null)
                throw new ArgumentNullException(nameof(highAlarmHysteresis), "Property is not nullable for class InstallationsIdSiteAlarmsPutRequest.");

            if (lowAlarm.IsSet && lowAlarm.Value == null)
                throw new ArgumentNullException(nameof(lowAlarm), "Property is not nullable for class InstallationsIdSiteAlarmsPutRequest.");

            if (lowAlarmHysteresis.IsSet && lowAlarmHysteresis.Value == null)
                throw new ArgumentNullException(nameof(lowAlarmHysteresis), "Property is not nullable for class InstallationsIdSiteAlarmsPutRequest.");

            if (enumValues.IsSet && enumValues.Value == null)
                throw new ArgumentNullException(nameof(enumValues), "Property is not nullable for class InstallationsIdSiteAlarmsPutRequest.");

            return new InstallationsIdSiteAlarmsPutRequest(idDataAttribute, instance, alarmEnabled, notifyAfterSeconds, highAlarm, highAlarmHysteresis, lowAlarm, lowAlarmHysteresis, enumValues);
        }

        /// <summary>
        /// Serializes a <see cref="InstallationsIdSiteAlarmsPutRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="installationsIdSiteAlarmsPutRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, InstallationsIdSiteAlarmsPutRequest installationsIdSiteAlarmsPutRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, installationsIdSiteAlarmsPutRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="InstallationsIdSiteAlarmsPutRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="installationsIdSiteAlarmsPutRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, InstallationsIdSiteAlarmsPutRequest installationsIdSiteAlarmsPutRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (installationsIdSiteAlarmsPutRequest.EnumValuesOption.IsSet && installationsIdSiteAlarmsPutRequest.EnumValues == null)
                throw new ArgumentNullException(nameof(installationsIdSiteAlarmsPutRequest.EnumValues), "Property is required for class InstallationsIdSiteAlarmsPutRequest.");

            if (installationsIdSiteAlarmsPutRequest.IdDataAttributeOption.IsSet)
                writer.WriteNumber("idDataAttribute", installationsIdSiteAlarmsPutRequest.IdDataAttributeOption.Value!.Value);

            if (installationsIdSiteAlarmsPutRequest.InstanceOption.IsSet)
                writer.WriteNumber("instance", installationsIdSiteAlarmsPutRequest.InstanceOption.Value!.Value);

            if (installationsIdSiteAlarmsPutRequest.AlarmEnabledOption.IsSet)
                writer.WriteNumber("AlarmEnabled", installationsIdSiteAlarmsPutRequest.AlarmEnabledOption.Value!.Value);

            if (installationsIdSiteAlarmsPutRequest.NotifyAfterSecondsOption.IsSet)
                writer.WriteNumber("NotifyAfterSeconds", installationsIdSiteAlarmsPutRequest.NotifyAfterSecondsOption.Value!.Value);

            if (installationsIdSiteAlarmsPutRequest.HighAlarmOption.IsSet)
                writer.WriteNumber("highAlarm", installationsIdSiteAlarmsPutRequest.HighAlarmOption.Value!.Value);

            if (installationsIdSiteAlarmsPutRequest.HighAlarmHysteresisOption.IsSet)
                writer.WriteNumber("highAlarmHysteresis", installationsIdSiteAlarmsPutRequest.HighAlarmHysteresisOption.Value!.Value);

            if (installationsIdSiteAlarmsPutRequest.LowAlarmOption.IsSet)
                writer.WriteNumber("lowAlarm", installationsIdSiteAlarmsPutRequest.LowAlarmOption.Value!.Value);

            if (installationsIdSiteAlarmsPutRequest.LowAlarmHysteresisOption.IsSet)
                writer.WriteNumber("lowAlarmHysteresis", installationsIdSiteAlarmsPutRequest.LowAlarmHysteresisOption.Value!.Value);

            if (installationsIdSiteAlarmsPutRequest.EnumValuesOption.IsSet)
            {
                writer.WritePropertyName("enumValues");
                JsonSerializer.Serialize(writer, installationsIdSiteAlarmsPutRequest.EnumValues, jsonSerializerOptions);
            }
        }
    }
}
