// <auto-generated>
/*
 * VRM API
 *
 * ## Introduction This document provides a brief overview of some of the available endpoints and their parameters. The API is a REST API, accepting JSON as request body. You can use the try-it tool to play around with it, or use software like Postman.  ## Authentication Most endpoints require authentication, using a JWT token. This token should be placed in the `x-authorization` field in the HTTP header. There are two types of tokens. - Bearer token. Uses the `Bearer <token_value>` format. This is used when logging in to VRM, for example. Can be retrieved from [/auth/login](/operations/auth/login) or [/auth/loginAsDemo](/operations/auth/loginAsDemo). - Access token. Uses the `Token <token_value>` format. This is commonly used for third party applications using the VRM API. Can be created using [/users/{idUser}/accesstokens/create](/operations/users/idUser/accesstokens/create).  ## Rate limiting Most endpoints are by default rate limited with a rolling window of max 200 requests, where every 0.33 seconds a request gets removed from the rolling window. (so on average maximum of 3 requests per second won't get rate limited). There are different types of ratelimiting in VRM. If you receive a 429 with a JSON response, you can check the Retry-After response header to check the amount of seconds you have to wait until retrying.  ## WARNING & DISCLAIMER Whilst publicly available, Victron Energy does not offer support to professional customers or end-users that implement features using the here documented functionality, except in really specific situations (i.e such as a special arrangement with a large OEM customer).  The recommended method for support on the VRM API is to use the Modifications section on Victron Community. This space is frequently visited by many people using the API, and other methods of integrating with Victron products. Direct company support is only offered on a limited basis via your Victron representative.
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// InstallationsIdSiteInvitePostRequest
    /// </summary>
    public partial class InstallationsIdSiteInvitePostRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InstallationsIdSiteInvitePostRequest" /> class.
        /// </summary>
        /// <param name="name">name</param>
        /// <param name="email">email</param>
        /// <param name="accessLevel">The access level the invited user should have. Value 0 gives demo rights, value 1 gives user rights, and value 2 gives admin rights.</param>
        [JsonConstructor]
        public InstallationsIdSiteInvitePostRequest(Option<string?> name = default, Option<string?> email = default, Option<decimal?> accessLevel = default)
        {
            NameOption = name;
            EmailOption = email;
            AccessLevelOption = accessLevel;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        /* <example>Andrew</example> */
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Email
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EmailOption { get; private set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        /* <example>andrew@example.com</example> */
        [JsonPropertyName("email")]
        public string? Email { get { return this.EmailOption; } set { this.EmailOption = new(value); } }

        /// <summary>
        /// Used to track the state of AccessLevel
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> AccessLevelOption { get; private set; }

        /// <summary>
        /// The access level the invited user should have. Value 0 gives demo rights, value 1 gives user rights, and value 2 gives admin rights.
        /// </summary>
        /// <value>The access level the invited user should have. Value 0 gives demo rights, value 1 gives user rights, and value 2 gives admin rights.</value>
        /* <example>1</example> */
        [JsonPropertyName("accessLevel")]
        public decimal? AccessLevel { get { return this.AccessLevelOption; } set { this.AccessLevelOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InstallationsIdSiteInvitePostRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  AccessLevel: ").Append(AccessLevel).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="InstallationsIdSiteInvitePostRequest" />
    /// </summary>
    public class InstallationsIdSiteInvitePostRequestJsonConverter : JsonConverter<InstallationsIdSiteInvitePostRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="InstallationsIdSiteInvitePostRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override InstallationsIdSiteInvitePostRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<string?> email = default;
            Option<decimal?> accessLevel = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "email":
                            email = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "accessLevel":
                            accessLevel = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class InstallationsIdSiteInvitePostRequest.");

            if (email.IsSet && email.Value == null)
                throw new ArgumentNullException(nameof(email), "Property is not nullable for class InstallationsIdSiteInvitePostRequest.");

            if (accessLevel.IsSet && accessLevel.Value == null)
                throw new ArgumentNullException(nameof(accessLevel), "Property is not nullable for class InstallationsIdSiteInvitePostRequest.");

            return new InstallationsIdSiteInvitePostRequest(name, email, accessLevel);
        }

        /// <summary>
        /// Serializes a <see cref="InstallationsIdSiteInvitePostRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="installationsIdSiteInvitePostRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, InstallationsIdSiteInvitePostRequest installationsIdSiteInvitePostRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, installationsIdSiteInvitePostRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="InstallationsIdSiteInvitePostRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="installationsIdSiteInvitePostRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, InstallationsIdSiteInvitePostRequest installationsIdSiteInvitePostRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (installationsIdSiteInvitePostRequest.NameOption.IsSet && installationsIdSiteInvitePostRequest.Name == null)
                throw new ArgumentNullException(nameof(installationsIdSiteInvitePostRequest.Name), "Property is required for class InstallationsIdSiteInvitePostRequest.");

            if (installationsIdSiteInvitePostRequest.EmailOption.IsSet && installationsIdSiteInvitePostRequest.Email == null)
                throw new ArgumentNullException(nameof(installationsIdSiteInvitePostRequest.Email), "Property is required for class InstallationsIdSiteInvitePostRequest.");

            if (installationsIdSiteInvitePostRequest.NameOption.IsSet)
                writer.WriteString("name", installationsIdSiteInvitePostRequest.Name);

            if (installationsIdSiteInvitePostRequest.EmailOption.IsSet)
                writer.WriteString("email", installationsIdSiteInvitePostRequest.Email);

            if (installationsIdSiteInvitePostRequest.AccessLevelOption.IsSet)
                writer.WriteNumber("accessLevel", installationsIdSiteInvitePostRequest.AccessLevelOption.Value!.Value);
        }
    }
}
