// <auto-generated>
/*
 * VRM API
 *
 * ## Introduction This document provides a brief overview of some of the available endpoints and their parameters. The API is a REST API, accepting JSON as request body. You can use the try-it tool to play around with it, or use software like Postman.  ## Authentication Most endpoints require authentication, using a JWT token. This token should be placed in the `x-authorization` field in the HTTP header. There are two types of tokens. - Bearer token. Uses the `Bearer <token_value>` format. This is used when logging in to VRM, for example. Can be retrieved from [/auth/login](/operations/auth/login) or [/auth/loginAsDemo](/operations/auth/loginAsDemo). - Access token. Uses the `Token <token_value>` format. This is commonly used for third party applications using the VRM API. Can be created using [/users/{idUser}/accesstokens/create](/operations/users/idUser/accesstokens/create).  ## Rate limiting Most endpoints are by default rate limited with a rolling window of max 200 requests, where every 0.33 seconds a request gets removed from the rolling window. (so on average maximum of 3 requests per second won't get rate limited). There are different types of ratelimiting in VRM. If you receive a 429 with a JSON response, you can check the Retry-After response header to check the amount of seconds you have to wait until retrying.  ## WARNING & DISCLAIMER Whilst publicly available, Victron Energy does not offer support to professional customers or end-users that implement features using the here documented functionality, except in really specific situations (i.e such as a special arrangement with a large OEM customer).  The recommended method for support on the VRM API is to use the Modifications section on Victron Community. This space is frequently visited by many people using the API, and other methods of integrating with Victron products. Direct company support is only offered on a limited basis via your Victron representative.
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// A single enum value.
    /// </summary>
    public partial class InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInnerEnumDataInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInnerEnumDataInner" /> class.
        /// </summary>
        /// <param name="nameEnum">Enum name.</param>
        /// <param name="valueEnum">Enum value.</param>
        /// <param name="values">Underlying values corresponding to this value, only for compounded settings.</param>
        [JsonConstructor]
        public InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInnerEnumDataInner(string nameEnum, int valueEnum, Option<Dictionary<string, int>?> values = default)
        {
            NameEnum = nameEnum;
            ValueEnum = valueEnum;
            ValuesOption = values;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Enum name.
        /// </summary>
        /// <value>Enum name.</value>
        [JsonPropertyName("nameEnum")]
        public string NameEnum { get; set; }

        /// <summary>
        /// Enum value.
        /// </summary>
        /// <value>Enum value.</value>
        [JsonPropertyName("valueEnum")]
        public int ValueEnum { get; set; }

        /// <summary>
        /// Used to track the state of Values
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, int>?> ValuesOption { get; private set; }

        /// <summary>
        /// Underlying values corresponding to this value, only for compounded settings.
        /// </summary>
        /// <value>Underlying values corresponding to this value, only for compounded settings.</value>
        [JsonPropertyName("values")]
        public Dictionary<string, int>? Values { get { return this.ValuesOption; } set { this.ValuesOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInnerEnumDataInner {\n");
            sb.Append("  NameEnum: ").Append(NameEnum).Append("\n");
            sb.Append("  ValueEnum: ").Append(ValueEnum).Append("\n");
            sb.Append("  Values: ").Append(Values).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInnerEnumDataInner" />
    /// </summary>
    public class InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInnerEnumDataInnerJsonConverter : JsonConverter<InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInnerEnumDataInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInnerEnumDataInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInnerEnumDataInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> nameEnum = default;
            Option<int?> valueEnum = default;
            Option<Dictionary<string, int>?> values = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "nameEnum":
                            nameEnum = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "valueEnum":
                            valueEnum = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "values":
                            values = new Option<Dictionary<string, int>?>(JsonSerializer.Deserialize<Dictionary<string, int>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!nameEnum.IsSet)
                throw new ArgumentException("Property is required for class InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInnerEnumDataInner.", nameof(nameEnum));

            if (!valueEnum.IsSet)
                throw new ArgumentException("Property is required for class InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInnerEnumDataInner.", nameof(valueEnum));

            if (nameEnum.IsSet && nameEnum.Value == null)
                throw new ArgumentNullException(nameof(nameEnum), "Property is not nullable for class InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInnerEnumDataInner.");

            if (valueEnum.IsSet && valueEnum.Value == null)
                throw new ArgumentNullException(nameof(valueEnum), "Property is not nullable for class InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInnerEnumDataInner.");

            if (values.IsSet && values.Value == null)
                throw new ArgumentNullException(nameof(values), "Property is not nullable for class InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInnerEnumDataInner.");

            return new InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInnerEnumDataInner(nameEnum.Value!, valueEnum.Value!.Value!, values);
        }

        /// <summary>
        /// Serializes a <see cref="InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInnerEnumDataInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="installationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInnerEnumDataInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInnerEnumDataInner installationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInnerEnumDataInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, installationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInnerEnumDataInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInnerEnumDataInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="installationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInnerEnumDataInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInnerEnumDataInner installationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInnerEnumDataInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (installationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInnerEnumDataInner.NameEnum == null)
                throw new ArgumentNullException(nameof(installationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInnerEnumDataInner.NameEnum), "Property is required for class InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInnerEnumDataInner.");

            if (installationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInnerEnumDataInner.ValuesOption.IsSet && installationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInnerEnumDataInner.Values == null)
                throw new ArgumentNullException(nameof(installationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInnerEnumDataInner.Values), "Property is required for class InstallationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInnerEnumDataInner.");

            writer.WriteString("nameEnum", installationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInnerEnumDataInner.NameEnum);

            writer.WriteNumber("valueEnum", installationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInnerEnumDataInner.ValueEnum);

            if (installationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInnerEnumDataInner.ValuesOption.IsSet)
            {
                writer.WritePropertyName("values");
                JsonSerializer.Serialize(writer, installationsIdSiteSystemOverview200ResponseRecordsDevicesInnerSettingsInnerEnumDataInner.Values, jsonSerializerOptions);
            }
        }
    }
}
