// <auto-generated>
/*
 * VRM API
 *
 * ## Introduction This document provides a brief overview of some of the available endpoints and their parameters. The API is a REST API, accepting JSON as request body. You can use the try-it tool to play around with it, or use software like Postman.  ## Authentication Most endpoints require authentication, using a JWT token. This token should be placed in the `x-authorization` field in the HTTP header. There are two types of tokens. - Bearer token. Uses the `Bearer <token_value>` format. This is used when logging in to VRM, for example. Can be retrieved from [/auth/login](/operations/auth/login) or [/auth/loginAsDemo](/operations/auth/loginAsDemo). - Access token. Uses the `Token <token_value>` format. This is commonly used for third party applications using the VRM API. Can be created using [/users/{idUser}/accesstokens/create](/operations/users/idUser/accesstokens/create).  ## Rate limiting Most endpoints are by default rate limited with a rolling window of max 200 requests, where every 0.33 seconds a request gets removed from the rolling window. (so on average maximum of 3 requests per second won't get rate limited). There are different types of ratelimiting in VRM. If you receive a 429 with a JSON response, you can check the Retry-After response header to check the amount of seconds you have to wait until retrying.  ## WARNING & DISCLAIMER Whilst publicly available, Victron Energy does not offer support to professional customers or end-users that implement features using the here documented functionality, except in really specific situations (i.e such as a special arrangement with a large OEM customer).  The recommended method for support on the VRM API is to use the Modifications section on Victron Community. This space is frequently visited by many people using the API, and other methods of integrating with Victron products. Direct company support is only offered on a limited basis via your Victron representative.
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Fetched graph data.
    /// </summary>
    public partial class InstallationsIdSiteWidgetsGraph200ResponseRecords : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InstallationsIdSiteWidgetsGraph200ResponseRecords" /> class.
        /// </summary>
        /// <param name="data">Data points per attribute.</param>
        /// <param name="meta">Meta data per attribute.</param>
        [JsonConstructor]
        public InstallationsIdSiteWidgetsGraph200ResponseRecords(Dictionary<string, List<List<decimal>>> data, Dictionary<string, InstallationsIdSiteWidgetsGraph200ResponseRecordsMetaValue> meta)
        {
            Data = data;
            Meta = meta;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Data points per attribute.
        /// </summary>
        /// <value>Data points per attribute.</value>
        [JsonPropertyName("data")]
        public Dictionary<string, List<List<decimal>>> Data { get; set; }

        /// <summary>
        /// Meta data per attribute.
        /// </summary>
        /// <value>Meta data per attribute.</value>
        [JsonPropertyName("meta")]
        public Dictionary<string, InstallationsIdSiteWidgetsGraph200ResponseRecordsMetaValue> Meta { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InstallationsIdSiteWidgetsGraph200ResponseRecords {\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  Meta: ").Append(Meta).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="InstallationsIdSiteWidgetsGraph200ResponseRecords" />
    /// </summary>
    public class InstallationsIdSiteWidgetsGraph200ResponseRecordsJsonConverter : JsonConverter<InstallationsIdSiteWidgetsGraph200ResponseRecords>
    {
        /// <summary>
        /// Deserializes json to <see cref="InstallationsIdSiteWidgetsGraph200ResponseRecords" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override InstallationsIdSiteWidgetsGraph200ResponseRecords Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Dictionary<string, List<List<decimal>>>?> data = default;
            Option<Dictionary<string, InstallationsIdSiteWidgetsGraph200ResponseRecordsMetaValue>?> meta = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "data":
                            data = new Option<Dictionary<string, List<List<decimal>>>?>(JsonSerializer.Deserialize<Dictionary<string, List<List<decimal>>>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "meta":
                            meta = new Option<Dictionary<string, InstallationsIdSiteWidgetsGraph200ResponseRecordsMetaValue>?>(JsonSerializer.Deserialize<Dictionary<string, InstallationsIdSiteWidgetsGraph200ResponseRecordsMetaValue>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!data.IsSet)
                throw new ArgumentException("Property is required for class InstallationsIdSiteWidgetsGraph200ResponseRecords.", nameof(data));

            if (!meta.IsSet)
                throw new ArgumentException("Property is required for class InstallationsIdSiteWidgetsGraph200ResponseRecords.", nameof(meta));

            if (data.IsSet && data.Value == null)
                throw new ArgumentNullException(nameof(data), "Property is not nullable for class InstallationsIdSiteWidgetsGraph200ResponseRecords.");

            if (meta.IsSet && meta.Value == null)
                throw new ArgumentNullException(nameof(meta), "Property is not nullable for class InstallationsIdSiteWidgetsGraph200ResponseRecords.");

            return new InstallationsIdSiteWidgetsGraph200ResponseRecords(data.Value!, meta.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="InstallationsIdSiteWidgetsGraph200ResponseRecords" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="installationsIdSiteWidgetsGraph200ResponseRecords"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, InstallationsIdSiteWidgetsGraph200ResponseRecords installationsIdSiteWidgetsGraph200ResponseRecords, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, installationsIdSiteWidgetsGraph200ResponseRecords, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="InstallationsIdSiteWidgetsGraph200ResponseRecords" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="installationsIdSiteWidgetsGraph200ResponseRecords"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, InstallationsIdSiteWidgetsGraph200ResponseRecords installationsIdSiteWidgetsGraph200ResponseRecords, JsonSerializerOptions jsonSerializerOptions)
        {
            if (installationsIdSiteWidgetsGraph200ResponseRecords.Data == null)
                throw new ArgumentNullException(nameof(installationsIdSiteWidgetsGraph200ResponseRecords.Data), "Property is required for class InstallationsIdSiteWidgetsGraph200ResponseRecords.");

            if (installationsIdSiteWidgetsGraph200ResponseRecords.Meta == null)
                throw new ArgumentNullException(nameof(installationsIdSiteWidgetsGraph200ResponseRecords.Meta), "Property is required for class InstallationsIdSiteWidgetsGraph200ResponseRecords.");

            writer.WritePropertyName("data");
            JsonSerializer.Serialize(writer, installationsIdSiteWidgetsGraph200ResponseRecords.Data, jsonSerializerOptions);
            writer.WritePropertyName("meta");
            JsonSerializer.Serialize(writer, installationsIdSiteWidgetsGraph200ResponseRecords.Meta, jsonSerializerOptions);
        }
    }
}
