// <auto-generated>
/*
 * VRM API
 *
 * ## Introduction This document provides a brief overview of some of the available endpoints and their parameters. The API is a REST API, accepting JSON as request body. You can use the try-it tool to play around with it, or use software like Postman.  ## Authentication Most endpoints require authentication, using a JWT token. This token should be placed in the `x-authorization` field in the HTTP header. There are two types of tokens. - Bearer token. Uses the `Bearer <token_value>` format. This is used when logging in to VRM, for example. Can be retrieved from [/auth/login](/operations/auth/login) or [/auth/loginAsDemo](/operations/auth/loginAsDemo). - Access token. Uses the `Token <token_value>` format. This is commonly used for third party applications using the VRM API. Can be created using [/users/{idUser}/accesstokens/create](/operations/users/idUser/accesstokens/create).  ## Rate limiting Most endpoints are by default rate limited with a rolling window of max 200 requests, where every 0.33 seconds a request gets removed from the rolling window. (so on average maximum of 3 requests per second won't get rate limited). There are different types of ratelimiting in VRM. If you receive a 429 with a JSON response, you can check the Retry-After response header to check the amount of seconds you have to wait until retrying.  ## WARNING & DISCLAIMER Whilst publicly available, Victron Energy does not offer support to professional customers or end-users that implement features using the here documented functionality, except in really specific situations (i.e such as a special arrangement with a large OEM customer).  The recommended method for support on the VRM API is to use the Modifications section on Victron Community. This space is frequently visited by many people using the API, and other methods of integrating with Victron products. Direct company support is only offered on a limited basis via your Victron representative.
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// InstallationsIdSiteStats200ResponseRecords
    /// </summary>
    public partial class InstallationsIdSiteStats200ResponseRecords : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InstallationsIdSiteStats200ResponseRecords" /> class.
        /// </summary>
        /// <param name="dictionary"></param>
        internal InstallationsIdSiteStats200ResponseRecords(Dictionary<string, InstallationsIdSiteStats200ResponseRecordsOneOfValue> dictionary)
        {
            Dictionary1 = dictionary;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InstallationsIdSiteStats200ResponseRecords" /> class.
        /// </summary>
        /// <param name="dictionary"></param>
        internal InstallationsIdSiteStats200ResponseRecords(Dictionary<string, InstallationsIdSiteStats200ResponseRecordsOneOfValue1> dictionary)
        {
            Dictionary2 = dictionary;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Statistics for each data attribute.
        /// </summary>
        /// <value>Statistics for each data attribute.</value>
        public Dictionary<string, InstallationsIdSiteStats200ResponseRecordsOneOfValue>? Dictionary1 { get; set; }

        /// <summary>
        /// List of instances, with the key or index being the instance id.
        /// </summary>
        /// <value>List of instances, with the key or index being the instance id.</value>
        public Dictionary<string, InstallationsIdSiteStats200ResponseRecordsOneOfValue1>? Dictionary2 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InstallationsIdSiteStats200ResponseRecords {\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="InstallationsIdSiteStats200ResponseRecords" />
    /// </summary>
    public class InstallationsIdSiteStats200ResponseRecordsJsonConverter : JsonConverter<InstallationsIdSiteStats200ResponseRecords>
    {
        /// <summary>
        /// Deserializes json to <see cref="InstallationsIdSiteStats200ResponseRecords" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override InstallationsIdSiteStats200ResponseRecords Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Dictionary<string, InstallationsIdSiteStats200ResponseRecordsOneOfValue>? dictionary1 = default;
            Dictionary<string, InstallationsIdSiteStats200ResponseRecordsOneOfValue1>? dictionary2 = default;

            Utf8JsonReader utf8JsonReaderOneOf = utf8JsonReader;
            while (utf8JsonReaderOneOf.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReaderOneOf.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReaderOneOf.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReaderOneOf.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReaderOneOf.CurrentDepth)
                    break;

                if (utf8JsonReaderOneOf.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReaderOneOf.CurrentDepth - 1)
                {
                    Utf8JsonReader utf8JsonReaderDictionary = utf8JsonReader;
                    ClientUtils.TryDeserialize<Dictionary<string, InstallationsIdSiteStats200ResponseRecordsOneOfValue>?>(ref utf8JsonReaderDictionary, jsonSerializerOptions, out dictionary1);

                    //Utf8JsonReader utf8JsonReaderDictionary = utf8JsonReader;
                    ClientUtils.TryDeserialize<Dictionary<string, InstallationsIdSiteStats200ResponseRecordsOneOfValue1>?>(ref utf8JsonReaderDictionary, jsonSerializerOptions, out dictionary2);
                }
            }

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        default:
                            break;
                    }
                }
            }

            if (dictionary1 != null)
                return new InstallationsIdSiteStats200ResponseRecords(dictionary1);

            if (dictionary2 != null)
                return new InstallationsIdSiteStats200ResponseRecords(dictionary2);

            throw new JsonException();
        }

        /// <summary>
        /// Serializes a <see cref="InstallationsIdSiteStats200ResponseRecords" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="installationsIdSiteStats200ResponseRecords"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, InstallationsIdSiteStats200ResponseRecords installationsIdSiteStats200ResponseRecords, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, installationsIdSiteStats200ResponseRecords, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="InstallationsIdSiteStats200ResponseRecords" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="installationsIdSiteStats200ResponseRecords"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, InstallationsIdSiteStats200ResponseRecords installationsIdSiteStats200ResponseRecords, JsonSerializerOptions jsonSerializerOptions)
        {

        }
    }
}
