// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Monitor.VrmApi.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class LoginOKResponse
    {
        /// <summary>
        /// Initializes a new instance of the LoginOKResponse class.
        /// </summary>
        public LoginOKResponse() { }

        /// <summary>
        /// Initializes a new instance of the LoginOKResponse class.
        /// </summary>
        public LoginOKResponse(string token, int idUser)
        {
            Token = token;
            IdUser = idUser;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "token")]
        public string Token { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "idUser")]
        public int IdUser { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Token == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Token");
            }
        }
    }
}
