// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Monitor.VrmApi.Models
{
    using Newtonsoft.Json;

    public partial class InstallationsOKResponseRecordsItemExtendedItem
    {
        /// <summary>
        /// Initializes a new instance of the
        /// InstallationsOKResponseRecordsItemExtendedItem class.
        /// </summary>
        public InstallationsOKResponseRecordsItemExtendedItem() { }

        /// <summary>
        /// Initializes a new instance of the
        /// InstallationsOKResponseRecordsItemExtendedItem class.
        /// </summary>
        public InstallationsOKResponseRecordsItemExtendedItem(int? idDataAttribute = default(int?), string code = default(string), string description = default(string), string formatWithUnit = default(string), string dataType = default(string), string textValue = default(string), string instance = default(string), string dbusServiceType = default(string), string dbusPath = default(string), string rawValue = default(string), string formattedValue = default(string))
        {
            IdDataAttribute = idDataAttribute;
            Code = code;
            Description = description;
            FormatWithUnit = formatWithUnit;
            DataType = dataType;
            TextValue = textValue;
            Instance = instance;
            DbusServiceType = dbusServiceType;
            DbusPath = dbusPath;
            RawValue = rawValue;
            FormattedValue = formattedValue;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "idDataAttribute")]
        public int? IdDataAttribute { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "code")]
        public string Code { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "formatWithUnit")]
        public string FormatWithUnit { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dataType")]
        public string DataType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "textValue")]
        public string TextValue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "instance")]
        public string Instance { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dbusServiceType")]
        public string DbusServiceType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dbusPath")]
        public string DbusPath { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "rawValue")]
        public string RawValue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "formattedValue")]
        public string FormattedValue { get; set; }

    }
}
